Add bmi-fortran and ecsimplesnow to build requirements
When these packages aren't listed in the build requirements, conda
can't reconcile `libgfortran` versions, producing this error message:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - ecsimplesnow -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - libgfortran[version='>=4.0.0,<5.0.0.a0']
```